# Site settings
title: DoHyeong Woo
description: DoHyeong Woo / ìš°ë„í˜•. Front-End Developer
url: https://wdh2100.github.io/

timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass

# User settings
username: DoHyeong Woo
user_title: Front-End Developer
user_description_kor: >
  ì €ëŠ” í”„ë¡ íŠ¸ ì—”ë“œ ê°œë°œì ìš°ë„í˜•ì…ë‹ˆë‹¤. ìƒˆë¡­ê³  ì‹ ê¸°í•˜ê³  í¥ë¯¸ë¡œìš´ê±¸ ì¢‹ì•„í•˜ê³  í•¨ê»˜ ì„±ì¥í•˜ëŠ” ë¬¸í™”ë¥¼ ì¢‹ì•„í•©ë‹ˆë‹¤.
  ì´ê²ƒ ì €ê²ƒ ë§ì´ ì¬ë¯¸ìˆê³  ì¦ê²ê²Œ ì‚´ì•„ê°€ê³  ì‹¶ìŠµë‹ˆë‹¤.
user_description_eng: >
  Hello ğŸ˜Š, I'm DoHyeong Woo, based in Korea.
  I am a passionate and creative Front-end Developer.

email: wdh2100@gmail.com
linkedin: ë„í˜•-ìš°-007b57105
github: wdh2100
